# Generated by Django 5.1.3 on 2025-01-02 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_id', models.IntegerField()),
                ('sender_group', models.CharField(max_length=1)),
                ('send_time', models.DateTimeField(auto_now_add=True)),
                ('text', models.CharField(max_length=150)),
                ('read_flag', models.BooleanField(default=False)),
            ],
        ),
    ]
