# Generated by Django 5.1.4 on 2025-01-20 11:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('chat_app', '0001_initial'),
        ('client_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='task',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='chat', to='client_app.task', verbose_name='チャット'),
        ),
    ]
