# Generated by Django 5.1.4 on 2025-01-13 08:48

import django.db.models.deletion
import edit_user_information_app.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('edit_user_information_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='customuser',
            managers=[
                ('objects', edit_user_information_app.models.UserManager()),
            ],
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='bank_number',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='username',
        ),
        migrations.AddField(
            model_name='customuser',
            name='bank_account_number',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='口座番号'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='bank_name',
            field=models.CharField(blank=True, max_length=60, null=True, verbose_name='銀行名'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='address',
            field=models.CharField(blank=True, max_length=150, verbose_name='住所'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='birthdate',
            field=models.DateField(blank=True, null=True, verbose_name='生年月日'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='branch_number',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='支店番号'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='email address'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='first_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='名前'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='The groups this user belongs to.', related_name='custom_user_groups', to='auth.group', verbose_name='groups'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='active'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='is_staff',
            field=models.BooleanField(default=False, verbose_name='staff status'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='last_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='名字'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='post_code',
            field=models.CharField(blank=True, max_length=15, verbose_name='郵便番号'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='street_address',
            field=models.CharField(blank=True, max_length=150, verbose_name='番地以下'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='telephone_number',
            field=models.CharField(blank=True, max_length=15, null=True, unique=True, verbose_name='電話番号'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='custom_user_permissions', to='auth.permission', verbose_name='user permissions'),
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=60, verbose_name='依頼件名')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='注文した時間')),
                ('limit_of_time', models.DateTimeField(blank=True, null=True, verbose_name='配達期限時間')),
                ('status', models.CharField(blank=True, max_length=1, null=True, verbose_name='配達ステータス')),
                ('shop_name', models.CharField(blank=True, max_length=150, null=True, verbose_name='店舗名')),
                ('delivery_completion_time', models.DateTimeField(blank=True, null=True, verbose_name='配達完了時間')),
                ('shop_post_code', models.CharField(blank=True, max_length=15, null=True, verbose_name='店舗の郵便番号')),
                ('shop_address', models.CharField(max_length=150, verbose_name='店舗の住所')),
                ('shop_street_address', models.CharField(max_length=150, verbose_name='店舗の番地')),
                ('client', models.ForeignKey(on_delete=models.SET(edit_user_information_app.models.get_sentinel_user), related_name='client_tasks', to=settings.AUTH_USER_MODEL, verbose_name='クライアント')),
                ('worker', models.ForeignKey(null=True, on_delete=models.SET(edit_user_information_app.models.get_sentinel_user), related_name='worker_tasks', to=settings.AUTH_USER_MODEL, verbose_name='配達員')),
            ],
        ),
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(verbose_name='申請時間')),
                ('price', models.IntegerField(verbose_name='申請金額')),
                ('status', models.CharField(max_length=1, verbose_name='申請ステータス')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requests', to='edit_user_information_app.task', verbose_name='申請')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=150, verbose_name='商品名')),
                ('price', models.IntegerField(verbose_name='単価')),
                ('quantity', models.IntegerField(verbose_name='個数')),
                ('notes', models.CharField(blank=True, max_length=150, null=True, verbose_name='備考')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='edit_user_information_app.task', verbose_name='商品')),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_cost', models.IntegerField(blank=True, null=True, verbose_name='合計金額')),
                ('courier_reward_amount', models.IntegerField(blank=True, null=True, verbose_name='給料')),
                ('delivery_fee', models.IntegerField(blank=True, null=True, verbose_name='配達手数料')),
                ('payment_fee', models.DateTimeField(blank=True, null=True, verbose_name='サービス代金支払い日付')),
                ('courier_item_payment_date', models.DateTimeField(blank=True, null=True, verbose_name='商品代金支払い日付')),
                ('courier_reward_date', models.DateTimeField(blank=True, null=True, verbose_name='報酬支払日付')),
                ('task', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='transaction', to='edit_user_information_app.task', verbose_name='関連するタスク')),
            ],
        ),
    ]
