# Generated by Django 5.1.4 on 2025-01-13 11:11

import send_contact_app.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=60, null=True, verbose_name='件名')),
                ('content', models.TextField(null=True, verbose_name='本文')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='問い合わせ日時')),
                ('user', models.ForeignKey(on_delete=models.SET(send_contact_app.models.get_sentinel_user), to=settings.AUTH_USER_MODEL, verbose_name='ユーザーID')),
            ],
        ),
    ]
