# Generated by Django 5.1.4 on 2025-01-06 07:00

import django.db.models.deletion
import send_contact_app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('send_contact_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomManager',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=150, verbose_name='アカウント名')),
                ('last_name', models.CharField(max_length=150, verbose_name='管理者の苗字')),
                ('first_name', models.CharField(max_length=150, verbose_name='管理者の名前')),
                ('is_staff', models.BooleanField(default=True, verbose_name='管理者であるかの識別')),
                ('is_active', models.BooleanField(default=True, verbose_name='アカウントが有効であるかの識別')),
            ],
        ),
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=150, verbose_name='名前')),
                ('last_name', models.CharField(max_length=150, verbose_name='苗字')),
                ('birth_date', models.DateField(verbose_name='生年月日')),
                ('post_code', models.CharField(max_length=15, verbose_name='郵便番号')),
                ('address', models.CharField(max_length=150, verbose_name='住所')),
                ('street_address', models.CharField(max_length=150, verbose_name='番地・丁名・建物名')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='メールアドレス')),
                ('telephone_number', models.CharField(max_length=15, unique=True, verbose_name='電話番号')),
                ('bank_number', models.CharField(blank=True, max_length=60, null=True, verbose_name='口座番号')),
                ('branch_number', models.CharField(blank=True, max_length=15, null=True, verbose_name='支店番号')),
            ],
        ),
        migrations.AlterField(
            model_name='contact',
            name='content',
            field=models.TextField(blank=True, null=True, verbose_name='本文'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='問い合わせ日時'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='title',
            field=models.CharField(blank=True, max_length=60, null=True, verbose_name='件名'),
        ),
        migrations.AddField(
            model_name='contact',
            name='user',
            field=models.ForeignKey(default=1, on_delete=models.SET(send_contact_app.models.get_sentinel_user), to='send_contact_app.customuser', verbose_name='ユーザーID'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=60, verbose_name='依頼件名')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='注文した時間')),
                ('limit_of_time', models.DateTimeField(blank=True, null=True, verbose_name='配達期限時間')),
                ('status', models.CharField(blank=True, max_length=1, null=True, verbose_name='配達ステータス')),
                ('shop_name', models.CharField(blank=True, max_length=150, null=True, verbose_name='店舗名')),
                ('delivery_completion_time', models.DateTimeField(blank=True, null=True, verbose_name='配達完了時間')),
                ('shop_post_code', models.CharField(blank=True, max_length=15, null=True, verbose_name='店舗の郵便番号')),
                ('shop_address', models.CharField(max_length=150, verbose_name='店舗の住所')),
                ('shop_street_address', models.CharField(max_length=150, verbose_name='店舗の番地')),
                ('client', models.ForeignKey(on_delete=models.SET(send_contact_app.models.get_sentinel_user), related_name='client', to='send_contact_app.customuser', verbose_name='クライアント')),
                ('worker_id', models.ForeignKey(null=True, on_delete=models.SET(send_contact_app.models.get_sentinel_user), related_name='worker', to='send_contact_app.customuser', verbose_name='配達員')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=150, verbose_name='商品名')),
                ('price', models.IntegerField(verbose_name='単価')),
                ('quantity', models.IntegerField(verbose_name='個数')),
                ('notes', models.CharField(blank=True, max_length=150, null=True, verbose_name='備考')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='send_contact_app.task', verbose_name='タスク')),
            ],
        ),
        migrations.CreateModel(
            name='Massage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender_group', models.CharField(max_length=1, verbose_name='送信者の属性')),
                ('send_time', models.DateTimeField(auto_now_add=True, verbose_name='メッセージ送信時間')),
                ('text', models.CharField(max_length=150, verbose_name='メッセージ文')),
                ('read_flag', models.BooleanField(default=False, verbose_name='既読フラグ')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='send_contact_app.task', verbose_name='タスク')),
            ],
        ),
        migrations.CreateModel(
            name='Transactions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_cost', models.IntegerField(blank=True, null=True, verbose_name='合計金額')),
                ('courier_reward_amount', models.IntegerField(blank=True, null=True, verbose_name='給料')),
                ('delivery_fee', models.IntegerField(blank=True, null=True, verbose_name='配達手数料')),
                ('payment_fee', models.DateTimeField(blank=True, null=True, verbose_name='サービス代金支払い日付')),
                ('courier_item_payment_date', models.DateTimeField(blank=True, null=True, verbose_name='商品代金支払い日付')),
                ('courier_reward_date', models.DateTimeField(blank=True, null=True, verbose_name='報酬支払日付')),
                ('task', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='transaction', to='send_contact_app.task', verbose_name='関連するタスク')),
            ],
        ),
    ]
