# Generated by Django 5.1.4 on 2025-01-09 04:27

import send_contact_app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('send_contact_app', '0004_alter_contact_title'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomManager',
        ),
        migrations.RemoveField(
            model_name='order',
            name='task',
        ),
        migrations.RemoveField(
            model_name='task',
            name='client',
        ),
        migrations.RemoveField(
            model_name='task',
            name='worker_id',
        ),
        migrations.RemoveField(
            model_name='transactions',
            name='task',
        ),
        migrations.AlterModelManagers(
            name='customuser',
            managers=[
                ('objects', send_contact_app.models.UserManager()),
            ],
        ),
        migrations.RenameField(
            model_name='customuser',
            old_name='birth_date',
            new_name='birthdate',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='bank_number',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='username',
        ),
        migrations.AddField(
            model_name='customuser',
            name='bank_account_number',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='口座番号'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='bank_name',
            field=models.CharField(blank=True, max_length=60, null=True, verbose_name='銀行名'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='content',
            field=models.TextField(null=True, verbose_name='本文'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='email address'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='last_name',
            field=models.CharField(max_length=150, verbose_name='名字'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='street_address',
            field=models.CharField(max_length=150, verbose_name='番地以下'),
        ),
        migrations.DeleteModel(
            name='Massage',
        ),
        migrations.DeleteModel(
            name='Order',
        ),
        migrations.DeleteModel(
            name='Task',
        ),
        migrations.DeleteModel(
            name='Transactions',
        ),
    ]
