# Generated by Django 5.1.4 on 2025-01-10 06:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Wokerapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='タイトル')),
                ('store_name', models.CharField(max_length=100, verbose_name='店舗名')),
                ('delivery_deadline', models.DateTimeField(verbose_name='配達期限')),
                ('delivery_address', models.CharField(max_length=255, verbose_name='配達先住所')),
                ('description', models.TextField(blank=True, verbose_name='備考')),
                ('status', models.CharField(choices=[('pending', '受付中'), ('accepted', '受注済み'), ('completed', '完了'), ('canceled', 'キャンセル')], default='pending', max_length=20, verbose_name='ステータス')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_requests', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '配達依頼',
                'verbose_name_plural': '配達依頼一覧',
            },
        ),
        migrations.CreateModel(
            name='DeliveryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=100, verbose_name='商品名')),
                ('quantity', models.IntegerField(verbose_name='数量')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='単価')),
                ('notes', models.TextField(blank=True, verbose_name='備考')),
                ('delivery_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='Wokerapp.deliveryrequest')),
            ],
            options={
                'verbose_name': '配達商品',
                'verbose_name_plural': '配達商品一覧',
            },
        ),
        migrations.CreateModel(
            name='DeliveryCost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='配達料金')),
                ('is_approved', models.BooleanField(default=False, verbose_name='承認済み')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('delivery_request', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cost', to='Wokerapp.deliveryrequest')),
            ],
            options={
                'verbose_name': '配達料金',
                'verbose_name_plural': '配達料金一覧',
            },
        ),
    ]
