# Generated by Django 5.1.4 on 2025-01-20 11:04

import client_app.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('client_app', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='client',
            field=models.ForeignKey(on_delete=models.SET(client_app.models.get_sentinel_user), related_name='client', to=settings.AUTH_USER_MODEL, verbose_name='クライアント'),
        ),
        migrations.AddField(
            model_name='task',
            name='worker',
            field=models.ForeignKey(blank=True, null=True, on_delete=models.SET(client_app.models.get_sentinel_user), related_name='worker', to=settings.AUTH_USER_MODEL, verbose_name='配達員'),
        ),
        migrations.AddField(
            model_name='request',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='request', to='client_app.task', verbose_name='申請'),
        ),
        migrations.AddField(
            model_name='order',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order', to='client_app.task', verbose_name='注文'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='task',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='transaction', to='client_app.task', verbose_name='関連するタスク'),
        ),
    ]
