# Generated by Django 3.2 on 2024-12-26 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login_app', '0002_alter_customuser_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='telephone_number',
            field=models.CharField(max_length=15, null=True, unique=True, verbose_name='電話番号'),
        ),
    ]
