# Generated by Django 3.2 on 2024-12-26 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login_app', '0003_customuser_telephone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='birth_date',
            field=models.DateField(blank=True, null=True, verbose_name='birth_date'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='other_adress',
            field=models.CharField(max_length=100, null=True, unique=True, verbose_name='番地、マンション名・部屋番号'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='town_area',
            field=models.CharField(max_length=100, null=True, unique=True, verbose_name='町域'),
        ),
    ]
