# Generated by Django 3.2 on 2024-12-26 06:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login_app', '0006_auto_20241226_1531'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='birth_date',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='other_adress',
        ),
    ]
