# Generated by Django 3.2 on 2024-12-26 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login_app', '0007_auto_20241226_1534'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='town_area',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='町域'),
        ),
    ]
