# Generated by Django 3.2 on 2024-12-28 07:24

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login_app', '0008_alter_customuser_town_area'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='town_area',
        ),
        migrations.AlterField(
            model_name='customuser',
            name='username',
            field=models.CharField(error_messages={'unique': 'このユーザーネームは既に使用されています。'}, help_text='150文字以内。日本語のみ使用可能です。', max_length=150, unique=True, validators=[django.core.validators.RegexValidator(message='ユーザーネームには日本語のみ使用できます。', regex='^[\\u4E00-\\u9FFF\\u3040-\\u309F\\u30A0-\\u30FF\\uFF00-\\uFFEFa-zA-Z0-9@.+-_]+$')], verbose_name='username'),
        ),
    ]
