# Generated by Django 3.2 on 2024-12-31 02:36

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login_app', '0009_auto_20241228_1624'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='birth_date',
            field=models.DateField(blank=True, null=True, verbose_name='生年月日'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='username',
            field=models.CharField(error_messages={'unique': 'このユーザーネームは既に使用されています。'}, help_text='150文字以内。日本語のみ使用可能です。', max_length=150, unique=True, validators=[django.core.validators.RegexValidator(message='ユーザーネームには日本語、アルファベット、数字、記号(@, ., +, -, _)のみ使用できます。', regex='^[\\u4E00-\\u9FFF\\u3040-\\u309F\\u30A0-\\u30FF\\uFF00-\\uFFEFa-zA-Z0-9@.+-_]+$')], verbose_name='username'),
        ),
    ]
