# Generated by Django 3.2 on 2024-12-31 03:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login_app', '0012_auto_20241231_1243'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='other_adress',
            new_name='other_address',
        ),
    ]
