# Generated by Django 3.2 on 2025-01-09 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login_app', '0013_rename_other_adress_customuser_other_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='first_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='姓'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='last_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='名'),
        ),
    ]
