# Generated by Django 3.2 on 2025-01-09 05:14

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login_app', '0019_alter_customuser_town_area'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='town_area',
            field=models.CharField(blank=True, help_text='高知県香美市土佐山田町の後の部分から記述してください。', max_length=150, null=True, validators=[django.core.validators.RegexValidator(message='町域には日本語、アルファベット、数字、記号(@, ., +, -, _)のみ使用できます。', regex='^[\\u4E00-\\u9FFF\\u3040-\\u309F\\u30A0-\\u30FF\\uFF00-\\uFFEFa-zA-Z0-9@.+-_]+$')], verbose_name='町域'),
        ),
    ]
