# Generated by Django 3.2 on 2025-01-10 07:48

from django.db import migrations, models
import login_app.models


class Migration(migrations.Migration):

    dependencies = [
        ('login_app', '0021_auto_20250109_1430'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='customuser',
            managers=[
                ('objects', login_app.models.UserManager()),
            ],
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='birth_date',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='other_address',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='town_area',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='username',
        ),
        migrations.AddField(
            model_name='customuser',
            name='address',
            field=models.CharField(max_length=150, null=True, verbose_name='住所'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='bank_account_number',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='口座番号'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='bank_name',
            field=models.CharField(blank=True, max_length=60, null=True, verbose_name='銀行名'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='birthdate',
            field=models.DateField(null=True, verbose_name='生年月日'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='branch_number',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='支店番号'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='post_code',
            field=models.CharField(max_length=15, null=True, verbose_name='郵便番号'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='street_address',
            field=models.CharField(max_length=150, null=True, verbose_name='番地以下'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='first_name',
            field=models.CharField(max_length=150, null=True, verbose_name='名前'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='last_name',
            field=models.CharField(max_length=150, null=True, verbose_name='名字'),
        ),
    ]
